<?php
    /**
     * This file is AUTOMATICALLY GENERATED. Do not edit manually. See thunderbirdBetaDetails.class.php for details.
     */
    require_once dirname(__FILE__).'/product-details/productDetails.class.php';

    define('LATEST_THUNDERBIRD_BETA_VERSION', '10.0b1');

    class thunderbirdBetaBuildDetails extends productDetails {

        var $primary_builds = array(
            'ar' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'ast' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.0))),
            'be' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.1))),
            'bg' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.4), 'OS X' => array('filesize' => 36.0), 'Linux' => array('filesize' => 18.4))),
            'bn-BD' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.2))),
            'br' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.8), 'OS X' => array('filesize' => 37.0), 'Linux' => array('filesize' => 19.4))),
            'ca' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.0))),
            'cs' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'da' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.5), 'OS X' => array('filesize' => 36.2), 'Linux' => array('filesize' => 18.6))),
            'de' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'el' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.0))),
            'en-GB' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.0))),
            'en-US' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.3), 'OS X' => array('filesize' => 35.9), 'Linux' => array('filesize' => 18.3))),
            'es-AR' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.0))),
            'es-ES' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.1))),
            'et' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'eu' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'fi' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'fr' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.4), 'OS X' => array('filesize' => 36.1), 'Linux' => array('filesize' => 18.4))),
            'fy-NL' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'ga-IE' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.0))),
            'gd' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.0))),
            'gl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.0))),
            'he' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'hu' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.7), 'OS X' => array('filesize' => 36.4), 'Linux' => array('filesize' => 18.6))),
            'id' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.2))),
            'is' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'it' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.1))),
            'ja' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.3), 'OS X' => array('filesize' => 36.0), 'Linux' => array('filesize' => 18.4))),
            'ko' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.0))),
            'lt' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.5), 'OS X' => array('filesize' => 36.1), 'Linux' => array('filesize' => 18.5))),
            'nb-NO' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.1))),
            'nl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.6), 'OS X' => array('filesize' => 36.3), 'Linux' => array('filesize' => 18.7))),
            'nn-NO' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'pa-IN' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'pl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 17.0), 'OS X' => array('filesize' => 36.7), 'Linux' => array('filesize' => 19.1))),
            'pt-BR' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'pt-PT' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.3), 'OS X' => array('filesize' => 35.9), 'Linux' => array('filesize' => 18.2))),
            'rm' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'ro' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.6), 'OS X' => array('filesize' => 36.3), 'Linux' => array('filesize' => 18.7))),
            'ru' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.5), 'OS X' => array('filesize' => 36.2), 'Linux' => array('filesize' => 18.5))),
            'si' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.2))),
            'sk' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.8), 'OS X' => array('filesize' => 36.6), 'Linux' => array('filesize' => 19.0))),
            'sl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'sq' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.7), 'Linux' => array('filesize' => 18.0))),
            'sr' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 17.3), 'OS X' => array('filesize' => 37.5), 'Linux' => array('filesize' => 20.0))),
            'sv-SE' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.5), 'OS X' => array('filesize' => 36.1), 'Linux' => array('filesize' => 18.4))),
            'ta-LK' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'tr' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'uk' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.6), 'OS X' => array('filesize' => 36.2), 'Linux' => array('filesize' => 18.6))),
            'vi' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.2), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.1))),
            'zh-CN' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.1), 'OS X' => array('filesize' => 35.8), 'Linux' => array('filesize' => 18.2))),
            'zh-TW' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 16.3), 'OS X' => array('filesize' => 36.0), 'Linux' => array('filesize' => 18.3)))
        );

        /**
         * Constructor.
         */
        function thunderbirdBetaBuildDetails() {
            parent::productDetails();
        }
    }
?>
