<?php
    /**
     * This file is AUTOMATICALLY GENERATED. Do not edit manually. See thunderbirdBetaDetails.class.php for details.
     */
    require_once dirname(__FILE__).'/product-details/productDetails.class.php';

    define('LATEST_THUNDERBIRD_BETA_VERSION', '8.0b2');

    class thunderbirdBetaBuildDetails extends productDetails {

        var $primary_builds = array(
            'ar' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'be' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'bg' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.3), 'OS X' => array('filesize' => 33.6), 'Linux' => array('filesize' => 17.3))),
            'bn-BD' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.4), 'Linux' => array('filesize' => 17.0))),
            'br' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.7), 'OS X' => array('filesize' => 34.5), 'Linux' => array('filesize' => 18.3))),
            'ca' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'cs' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'da' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.5), 'OS X' => array('filesize' => 33.8), 'Linux' => array('filesize' => 17.5))),
            'de' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'el' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'en-GB' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.0), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'en-US' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.2), 'OS X' => array('filesize' => 33.5), 'Linux' => array('filesize' => 17.2))),
            'es-AR' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 16.9))),
            'es-ES' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.0), 'OS X' => array('filesize' => 33.2), 'Linux' => array('filesize' => 16.9))),
            'et' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'eu' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 16.9))),
            'fi' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'fr' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.3), 'OS X' => array('filesize' => 33.6), 'Linux' => array('filesize' => 17.3))),
            'fy-NL' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'ga-IE' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'gd' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'gl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'he' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'hu' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.6), 'OS X' => array('filesize' => 33.9), 'Linux' => array('filesize' => 17.6))),
            'id' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.4), 'Linux' => array('filesize' => 17.1))),
            'is' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'it' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.0), 'OS X' => array('filesize' => 33.2), 'Linux' => array('filesize' => 16.9))),
            'ja' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.3), 'OS X' => array('filesize' => 33.6), 'Linux' => array('filesize' => 17.2))),
            'ko' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.0), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 16.9))),
            'lt' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.5), 'OS X' => array('filesize' => 33.8), 'Linux' => array('filesize' => 17.4))),
            'nb-NO' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'nl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.6), 'OS X' => array('filesize' => 33.9), 'Linux' => array('filesize' => 17.6))),
            'nn-NO' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 16.9))),
            'pa-IN' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.1))),
            'pl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.9), 'OS X' => array('filesize' => 34.3), 'Linux' => array('filesize' => 18.0))),
            'pt-BR' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'pt-PT' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.2), 'OS X' => array('filesize' => 33.5), 'Linux' => array('filesize' => 17.2))),
            'rm' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'ro' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.5), 'OS X' => array('filesize' => 33.9), 'Linux' => array('filesize' => 17.6))),
            'ru' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.5), 'OS X' => array('filesize' => 33.8), 'Linux' => array('filesize' => 17.4))),
            'si' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.4), 'Linux' => array('filesize' => 17.0))),
            'sk' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.7), 'OS X' => array('filesize' => 34.1), 'Linux' => array('filesize' => 17.8))),
            'sl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'sq' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.0), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 16.9))),
            'sv-SE' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.4), 'OS X' => array('filesize' => 33.7), 'Linux' => array('filesize' => 17.3))),
            'ta-LK' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.4), 'Linux' => array('filesize' => 17.0))),
            'tr' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'uk' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.5), 'OS X' => array('filesize' => 33.8), 'Linux' => array('filesize' => 17.4))),
            'vi' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.4), 'Linux' => array('filesize' => 17.0))),
            'zh-CN' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.1), 'OS X' => array('filesize' => 33.3), 'Linux' => array('filesize' => 17.0))),
            'zh-TW' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 15.2), 'OS X' => array('filesize' => 33.5), 'Linux' => array('filesize' => 17.3)))
        );

        /**
         * Constructor.
         */
        function thunderbirdBetaBuildDetails() {
            parent::productDetails();
        }
    }
?>
