<?php
    /**
     * This file is AUTOMATICALLY GENERATED. Do not edit manually. See thunderbirdBetaDetails.class.php for details.
     */
    require_once dirname(__FILE__).'/product-details/productDetails.class.php';

    define('LATEST_THUNDERBIRD_BETA_VERSION', '6.0b1');

    class thunderbirdBetaBuildDetails extends productDetails {

        var $primary_builds = array(
            'br' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.8), 'OS X' => array('filesize' => 32.3), 'Linux' => array('filesize' => 18.8))),
            'ca' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'cs' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'da' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.6), 'OS X' => array('filesize' => 31.6), 'Linux' => array('filesize' => 18.0))),
            'de' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'en-GB' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'en-US' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.4), 'OS X' => array('filesize' => 31.3), 'Linux' => array('filesize' => 17.7))),
            'es-AR' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'es-ES' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.1), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'et' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'eu' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'fi' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'fr' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.5), 'OS X' => array('filesize' => 31.5), 'Linux' => array('filesize' => 17.9))),
            'fy-NL' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'ga-IE' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'gd' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'gl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'he' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'is' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.5))),
            'it' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.1), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'ja' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.4), 'OS X' => array('filesize' => 0.0), 'Linux' => array('filesize' => 17.8))),
            'ko' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.1), 'Linux' => array('filesize' => 17.5))),
            'lt' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.6), 'OS X' => array('filesize' => 31.6), 'Linux' => array('filesize' => 18.0))),
            'nl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.7), 'OS X' => array('filesize' => 31.7), 'Linux' => array('filesize' => 18.1))),
            'pl' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 13.0), 'OS X' => array('filesize' => 32.1), 'Linux' => array('filesize' => 18.6))),
            'pt-BR' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.6))),
            'pt-PT' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.4), 'OS X' => array('filesize' => 31.3), 'Linux' => array('filesize' => 17.7))),
            'rm' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.6))),
            'ru' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.6), 'OS X' => array('filesize' => 31.6), 'Linux' => array('filesize' => 18.0))),
            'si' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.3), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.6))),
            'sk' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.9), 'OS X' => array('filesize' => 32.0), 'Linux' => array('filesize' => 18.4))),
            'sv-SE' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.5), 'OS X' => array('filesize' => 31.5), 'Linux' => array('filesize' => 17.9))),
            'ta-LK' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.3), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.6))),
            'uk' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.6), 'OS X' => array('filesize' => 31.6), 'Linux' => array('filesize' => 18.0))),
            'vi' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.2), 'OS X' => array('filesize' => 31.2), 'Linux' => array('filesize' => 17.6))),
            'zh-TW' => array(LATEST_THUNDERBIRD_BETA_VERSION  => array('Windows' => array('filesize'  => 12.4), 'OS X' => array('filesize' => 31.4), 'Linux' => array('filesize' => 17.8)))
        );

        /**
         * Constructor.
         */
        function thunderbirdBetaBuildDetails() {
            parent::productDetails();
        }
    }
?>
