#!/usr/bin/perl -w

system("./gen-ng-info raw-ng-list.txt > out.html");
system("../../credits/replace-between index.html '<!--BEGIN_LIST-->' '<!--END_LIST-->' out.html");

system("svn ci index.html raw-ng-list.txt");
