  <style type="text/css">
body {
  margin: 0;
  padding: 0;
  background: #fff url(/img/thunderbird/start/feature-background.jpg) top center no-repeat;
  color: #333;
  font-family: georgia, serif;
  font-size: small;
  line-height: 1.5;
  min-width: 790px;
}
html {
  min-width: 790px;
}

a:link,
a:visited {
  text-decoration: none;
  color: #c2550a;
}

a:hover,
a:active {
  text-decoration: underline;
  color: #c2550a;
}

#contents {
  margin: 0 auto;
  width: 780px;
  min-width: 780px;
  padding-left: 20px;
}

html[dir=rtl] #contents {
  padding:0;
  margin:0;
  padding-right:50%;
  min-width: 50%;
  width: 50%;
}

#header h1 {
  margin: 0 0 10px 0;
  padding: 50px 0 0 0;
  font-weight: normal;
  font-size: 330%;
  letter-spacing: -1px;
}

#header p {
  max-width: 455px;
  font-size: 135%;
}

p,
ul {
  max-width: 400px;
  font-size: 110%;
}

ul {
  margin-left: -10px;
  padding-left: 0;
}

ul li {
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAADCAMAAABh9kWNAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFaWRbAAAA+iK+cwAAAA5JREFUeNpiYEAAgAADAAAMAAFkFId7AAAAAElFTkSuQmCC);
  background-position: 0 12px;
  background-repeat: no-repeat;
  list-style-type: none;
  padding: 2px 0 4px 10px;
}

#footer {
  font-size: x-small;
  color: #999;
}
  </style>