  <style type="text/css">
  body {
    margin: 0;
    padding: 0;
    background: #fff url(<?php echo data_url("{$config['file_root']}/img/thunderbird/start/bg-header-small.jpg",'image/jpeg'); ?>) repeat-x;
    color: #3C475B;
    font-family: "segoe ui", tahoma, sans-serif;
    font-size: small;
    line-height: 1.5;
    min-width: 500px;
  }
  h1 {
    color:#0A4E96;
    font-family: arial, serif;
    text-shadow: 0 1px 1px #74768F;
    font-weight: bold;
  }
  h2 {
    font-size: small;
    line-height: 1.5;
  }
  a:link    { color: #0a4e96; }
  a:visited { color: #0a4e96; }
  a:hover   { color: #333; }
  a:active  { color: #000; }

  #contents {
    margin: 0;
    padding: 1em 250px 1em 2em;
    background: url(<?php echo data_url("{$config['file_root']}/img/thunderbird/start/main-feature.jpg",'image/jpeg'); ?>) top right no-repeat;
  }

  #header h1 {
    margin: 0;
    padding: 20px 0 0 0;
  }

  #header p {
    font-weight: bold;
    margin: 0;
    padding: 0 0 40px 0;
    max-width: 500px;
  }

  #footer {
    font-size: x-small;
    color: #999;
  }
  </style>